name: Build Windows executable

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install pyinstaller
      - name: Build executable
        run: pyinstaller --noconfirm --onefile --windowed --name MangaDexLibrary gui.py
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/MangaDexLibrary.exe
          asset_name: MangaDexLibrary.exe
          asset_content_type: application/octet-stream
